DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;

CREATE TABLE roles (
id INT AUTO_INCREMENT PRIMARY KEY,
rolename VARCHAR(15) NOT NULL
);

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
pseudo VARCHAR(30) NOT NULL,
password VARCHAR(200) NOT NULL,
mail VARCHAR(200) NOT NULL,
corn INT DEFAULT 0 NOT NULL,
id_roles INT,
FOREIGN KEY (id_roles) REFERENCES roles(id),
);