DROP TABLE IF EXISTS rules;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS guilds_j;
DROP TABLE IF EXISTS quests;
DROP TABLE IF EXISTS guilds_pnj;
DROP TABLE IF EXISTS roles;


CREATE TABLE roles (
id INT AUTO_INCREMENT PRIMARY KEY,
rolename VARCHAR(15) NOT NULL
);

CREATE TABLE guilds_pnj (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description VARCHAR(200) NOT NULL,
logo VARCHAR(200) NOT NULL
);

CREATE TABLE quests (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
description_j VARCHAR(255) NOT NULL,
description_pnj VARCHAR(255) NOT NULL,
reward INT DEFAULT 0 NOT NULL,
id_guilds_pnj INT DEFAULT NULL,
FOREIGN KEY (id_guilds_pnj) REFERENCES guilds_pnj(id)
);

CREATE TABLE guilds_j (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
description VARCHAR(255) NOT NULL,
id_quest INT DEFAULT NULL,
FOREIGN KEY (id_quest) REFERENCES quests(id)
);

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
pseudo VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
mail VARCHAR(255) NOT NULL,
corn INT DEFAULT 0 NOT NULL,
id_roles INT,
id_guilds_j INT DEFAULT NULL,
FOREIGN KEY (id_roles) REFERENCES roles(id),
FOREIGN KEY (id_guilds_j) REFERENCES guilds_j(id)
);

CREATE TABLE rules (
id INT AUTO_INCREMENT PRIMARY KEY,
description VARCHAR(255) NOT NULL
);